DATA_DIR=dataset/countdown-base
BASE_MODEL=Qwen/Qwen2.5-3B
N_GPUS=8
MODEL_ARCH=qwen2

python -m verl.trainer.main_ppo \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_batch_size=256 \
    data.max_prompt_length=256 \
    data.max_response_length=1024 \
    data.dataloader_num_workers=0 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.clip_ratio=0.2 \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.shuffle=True \
    +actor_rollout_ref.actor.data_loader_seed=42 \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.model.use_liger=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.rollout.name=kt \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.val_kwargs.n=8 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
    actor_rollout_ref.rollout.val_kwargs.top_k=20 \
    +actor_rollout_ref.rollout.unshard_fsdp_params=False \
    +actor_rollout_ref.rollout.offload_to_cpu=False \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    algorithm.adv_estimator=grpo \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb','console'] \
    trainer.total_training_steps=500 \
    trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=$N_GPUS \
    trainer.nnodes=1 \
    trainer.save_freq=500 \
    trainer.test_freq=10 \
    trainer.project_name=SampleRL \
    trainer.experiment_name=$EXPERIMENT_NAME \
    +actor_rollout_ref.rollout.kt.max_n_branch_per_token=2 \
    +actor_rollout_ref.rollout.kt.enable_param_scheduler=False \
    +actor_rollout_ref.rollout.kt.prob_filter_abs_thres=0.25 \
    +actor_rollout_ref.rollout.kt.prob_filter_rel_thres=0.15 \
    +actor_rollout_ref.rollout.kt.rollout_filter_edit_dist_thres=0.4 \
    +actor_rollout_ref.rollout.kt.rollout_filter_steps="[20,30,50]" \
    +actor_rollout_ref.rollout.kt.mix_ratio_schedule="{0:1,10:0.75,20:0.5,80:0.25,200:0}" \
    +actor_rollout_ref.rollout.kt.return_nb_thres_decay=0.05 \
    +actor_rollout_ref.rollout.kt.force_return_step=512 \
    2>&1 | tee $EXPERIMENT_NAME.log
